modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "tiab"
version = "${version}"
displayName = "Time In A Bottle"
authors = "haoict"
description = '''
This item allows you to accelerate the rate at which blocks tick.
It passively collects time while in your inventory which you can consume by right clicking a block with it.
The first click requires 30 Seconds, the second 60, the third 120 the fourth 240 and the fifth 480.
The speed at which the block ticks doubles with each click. The effect lasts 30 seconds.

Original by Random Things Mod (Owner: Lumien231). This is ported standalone version to 1.18.
'''
logoFile="tiab-logo.png"
credits="Random things by lumien"

[[dependencies.tiab]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tiab]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"