modLoader="javafml" #mandatory
license="MIT"
loaderVersion="[41,)" #mandatory

[[mods]] #mandatory
modId="tiab" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Time In A Bottle" #mandatory
logoFile="tiab-logo.png" #optional
credits="Random things by lumien" #optional
authors="haoict" #optional
description='''
This item allows you to accelerate the rate at which blocks tick.
It passively collects time while in your inventory which you can consume by right clicking a block with it.
The first click requires 30 Seconds, the second 60, the third 120 the fourth 240 and the fifth 480.
The speed at which the block ticks doubles with each click. The effect lasts 30 seconds.

Original by Random Things Mod (Owner: Lumien231). This is ported standalone version to 1.18.
'''
